version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: diploma_database
    environment:
      POSTGRES_USER: unforgettable
      POSTGRES_PASSWORD: 27092100
      POSTGRES_DB: diploma_database
    #    volumes:
    #      - postgres:/data/postgres
    ports:
      - "5432:5432"
    #    networks:
    #      - postgres
    restart: unless-stopped