server:
  port: 8080
spring:
  application:
    name: security_diploma
  datasource:
    username: 'unforgettable'
    password: '27092100'
    url: jdbc:postgresql://localhost:5432/security_diploma
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/security_diploma
    user: 'unforgettable'
    password: '27092100'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true